import { useEffect, useRef, useState } from "react";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { appendAuditEvent } from "@/lib/audit";
import { invokeProtectedFunction } from "@/lib/protectedInvoke";
import { toast } from "sonner";
import { jsPDF } from "jspdf";

interface HtmlExportMeta {
  filename: string;
  url: string;
}

const SubmitPanel = () => {
  const ws = useWorkspace();
  const [agreed, setAgreed] = useState(false);
  const htmlExportRef = useRef<HtmlExportMeta | null>(null);

  useEffect(() => {
    return () => {
      if (htmlExportRef.current?.url) {
        URL.revokeObjectURL(htmlExportRef.current.url);
      }
    };
  }, []);

  const buildHtmlExport = (download: boolean): HtmlExportMeta => {
    if (htmlExportRef.current?.url) {
      URL.revokeObjectURL(htmlExportRef.current.url);
    }

    const title = ws.currentBrief?.projectTitle || "Company Name Project";
    const goal = ws.currentBrief?.goal || "";
    const sections = ws.currentBrief?.contentSections?.length
      ? ws.currentBrief.contentSections
      : (ws.currentBrief?.keyMessages || []);
    const bodyBlocks = [
      goal,
      ...sections,
    ].filter(Boolean);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    *{box-sizing:border-box} body{margin:0;font-family:Arial,sans-serif;background:#f8fafc;color:#0f172a}
    header{background:#003087;color:#fff;padding:24px 28px}
    h1{margin:0;font-size:30px;line-height:1.2}
    main{max-width:980px;margin:24px auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:24px}
    p{line-height:1.7;margin:0 0 14px}
    footer{margin-top:20px;color:#64748b;font-size:12px}
  </style>
</head>
<body>
  <header>
    <h1>${title}</h1>
  </header>
  <main>
    ${bodyBlocks.map(block => `<p>${block}</p>`).join("\n    ")}
    <footer>Layout: ${ws.layout || "hero"} · Generated by Prompt Muse</footer>
  </main>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    const filename = `${safeTitle || "company-name-project"}.html`;

    if (download) {
      const a = document.createElement("a");
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      a.remove();
      toast.success("HTML export downloaded");
    }

    const meta = { filename, url };
    htmlExportRef.current = meta;
    return meta;
  };

  const wrapText = (pdf: jsPDF, text: string, x: number, y: number, maxWidth: number, lineHeight = 5) => {
    const lines = pdf.splitTextToSize(text, maxWidth) as string[];
    lines.forEach(line => {
      pdf.text(line, x, y);
      y += lineHeight;
    });
    return y;
  };

  const downloadPieReportPdf = (submittedAt: Date, htmlMeta?: HtmlExportMeta | null) => {
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const left = 14;
    const right = 196;
    const maxWidth = right - left;
    let y = 16;

    const projectTitle = ws.currentBrief?.projectTitle || "Untitled Project";
    const submitter = `${ws.user?.firstName || ""} ${ws.user?.lastName || ""}`.trim() || "Unknown";
    const email = ws.user?.email || "Unknown";
    const homeRegion = ws.user?.country || "Unknown";
    const targetRegion = ws.pieResult?.jurisdiction?.country_detected || homeRegion;
    const buildType = ws.prelim.buildType || "Unknown";
    const audience = ws.prelim.audience || "Unknown";
    const score = ws.reviewData?.overallScore || 0;
    const scoreCard = ws.reviewData?.scores || { compliance: 0, grammar: 0, brandVoice: 0, accessibility: 0 };
    const submittedAtIso = submittedAt.toISOString();
    const submittedAtLocal = submittedAt.toLocaleString();

    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("PIE Report", left, y);
    y += 8;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y = wrapText(doc, `Project: ${projectTitle}`, left, y, maxWidth);
    y += 2;

    doc.setDrawColor(220, 220, 220);
    doc.line(left, y, right, y);
    y += 7;

    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("Submission Details", left, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y = wrapText(doc, `Submitter: ${submitter}`, left, y, maxWidth);
    y = wrapText(doc, `Email: ${email}`, left, y, maxWidth);
    y = wrapText(doc, `Home Region: ${homeRegion}`, left, y, maxWidth);
    y = wrapText(doc, `Target Region: ${targetRegion}`, left, y, maxWidth);
    y = wrapText(doc, `Build Type: ${buildType}`, left, y, maxWidth);
    y = wrapText(doc, `Audience: ${audience}`, left, y, maxWidth);
    y = wrapText(doc, `Submission Timestamp (Local): ${submittedAtLocal}`, left, y, maxWidth);
    y = wrapText(doc, `Submission Timestamp (ISO): ${submittedAtIso}`, left, y, maxWidth);

    y += 3;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("PIE Scorecard", left, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    y = wrapText(doc, `Overall Score: ${score}/100`, left, y, maxWidth);
    y = wrapText(doc, `Compliance: ${scoreCard.compliance}/100`, left, y, maxWidth);
    y = wrapText(doc, `Grammar: ${scoreCard.grammar}/100`, left, y, maxWidth);
    y = wrapText(doc, `Brand Voice: ${scoreCard.brandVoice}/100`, left, y, maxWidth);
    y = wrapText(doc, `Accessibility: ${scoreCard.accessibility}/100`, left, y, maxWidth);

    y += 3;
    doc.setFont("helvetica", "bold");
    doc.setFontSize(12);
    doc.text("HTML Export", left, y);
    y += 6;

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    if (htmlMeta?.filename) {
      y = wrapText(doc, `File: ${htmlMeta.filename}`, left, y, maxWidth);
    } else {
      y = wrapText(doc, "File: No HTML export generated yet", left, y, maxWidth);
    }
    if (htmlMeta?.url) {
      doc.textWithLink("Open HTML download link", left, y, { url: htmlMeta.url });
      y += 5;
      y = wrapText(doc, htmlMeta.url, left, y, maxWidth);
    } else {
      y = wrapText(doc, "Link: Not available", left, y, maxWidth);
    }

    y += 4;
    doc.setTextColor(100, 100, 100);
    doc.setFontSize(9);
    wrapText(doc, "Generated by Prompt Intelligence Engine submission flow.", left, y, maxWidth);

    const safeTitle = projectTitle.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    doc.save(`${safeTitle || "project"}-pie-report.pdf`);
  };

  const handleExportHtml = () => {
    buildHtmlExport(true);
  };

  const handleDownloadPieReport = () => {
    const now = new Date();
    const htmlMeta = htmlExportRef.current || buildHtmlExport(false);
    downloadPieReportPdf(now, htmlMeta);
    toast.success("PIE Report downloaded");
  };

  const handleSubmit = async () => {
    if (!agreed) return;
    const submittedAt = new Date();
    const htmlMeta = buildHtmlExport(true);

    const payload = {
      projectTitle: ws.currentBrief?.projectTitle || "Untitled Project",
      submitter: `${ws.user?.firstName || ""} ${ws.user?.lastName || ""}`.trim(),
      submitterEmail: ws.user?.email || "",
      country: ws.user?.country || "",
      buildType: ws.prelim.buildType || "",
      score: ws.reviewData?.overallScore || 0,
    };

    try {
        const { data, error } = await invokeProtectedFunction("notify-reviewer", payload);
      if (error) throw new Error(error.message);
      appendAuditEvent({
        eventType: "notification",
        actor: ws.user?.email || "unknown-user",
        details: {
          reviewer_notified: true,
          simulated: Boolean(data?.simulated),
          message: data?.message || null,
        },
      });
      if (data?.simulated) {
        toast.message("Reviewer notification simulated (configure env vars for live email)");
      } else {
        toast.success("Reviewer notification sent");
      }
    } catch (err: any) {
      appendAuditEvent({
        eventType: "notification",
        actor: ws.user?.email || "unknown-user",
        details: {
          reviewer_notified: false,
          error: err?.message || "Notification call failed",
        },
      });
    }

    ws.setSubmitted();
    appendAuditEvent({
      eventType: "submission",
      actor: ws.user?.email || "unknown-user",
      details: {
        projectTitle: ws.currentBrief?.projectTitle || "Untitled Project",
        score: ws.reviewData?.overallScore || 0,
        buildType: ws.prelim.buildType || "",
        audience: ws.prelim.audience || "",
        submittedAt: submittedAt.toISOString(),
        htmlFile: htmlMeta.filename,
      },
    });
    downloadPieReportPdf(submittedAt, htmlMeta);
    toast.success("Project submitted for review!");
  };

  return (
    <div className="flex-1 flex items-center justify-center overflow-y-auto p-7 animate-fade-up">
      <div className="bg-card border-[1.5px] border-border rounded-[20px] shadow-pf-md p-9 max-w-[500px] w-full">
        <h2 className="font-serif text-xl text-pf-dark mb-1">Export and Submit</h2>
        <p className="text-[13px] text-muted-foreground mb-5">
          Export the generated page as HTML, then submit for final review.
        </p>

        <div className="grid grid-cols-2 gap-2 mb-4">
          <MetaBox label="Type" value={ws.prelim.buildType || "—"} />
          <MetaBox label="Audience" value={ws.prelim.audience || "—"} />
          <MetaBox label="Region" value={ws.user?.country || "—"} />
          <MetaBox label="Score" value={ws.reviewData ? `${ws.reviewData.overallScore}/100` : "—"} />
        </div>

        <div className="bg-secondary border border-border rounded-md p-3 text-[12.5px] text-muted-foreground leading-relaxed max-h-[120px] overflow-y-auto mb-3">
          By submitting this project, I confirm that all content has been reviewed for brand compliance,
          accessibility standards (WCAG 2.1 AA), and regulatory requirements applicable to the target
          jurisdiction. I understand that the IT review team will perform a final assessment before
          publication. Any content flagged during the automated review has been addressed or acknowledged.
          This submission is subject to Company Name internal content governance policy.
        </div>

        <label className="flex items-center gap-2.5 mb-5 cursor-pointer">
          <input
            type="checkbox"
            checked={agreed}
            onChange={e => setAgreed(e.target.checked)}
            className="w-[15px] h-[15px] accent-primary cursor-pointer"
          />
          <span className="text-[13px] font-medium text-foreground">I agree to the terms and conditions</span>
        </label>

        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={handleDownloadPieReport}
            className="w-full bg-card border border-border text-foreground rounded-md py-3 text-sm font-bold hover:border-primary hover:text-primary transition-all"
          >
            Download PIE Report
          </button>
          <button
            onClick={handleExportHtml}
            className="w-full bg-card border border-border text-foreground rounded-md py-3 text-sm font-bold hover:border-primary hover:text-primary transition-all"
          >
            Export HTML
          </button>
          <button
            onClick={handleSubmit}
            disabled={!agreed}
            className="w-full bg-btn-gradient text-primary-foreground rounded-md py-3 text-sm font-bold shadow-pf hover:shadow-pf-md transition-all disabled:opacity-40 disabled:cursor-not-allowed col-span-2"
          >
            Submit for Review
          </button>
        </div>
      </div>
    </div>
  );
};

function MetaBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-secondary border border-border rounded-md p-2.5">
      <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/60 mb-0.5">{label}</div>
      <div className="text-[13px] font-semibold text-foreground">{value}</div>
    </div>
  );
}

export default SubmitPanel;
