import { useState } from "react";
import { useWorkspace } from "@/contexts/WorkspaceContext";
import { supabase } from "@/integrations/supabase/client";
import { appendAuditEvent, exportAuditJsonl } from "@/lib/audit";
import { toast } from "sonner";

const SubmitPanel = () => {
  const ws = useWorkspace();
  const [agreed, setAgreed] = useState(false);

  const handleExportHtml = () => {
    const title = ws.currentBrief?.projectTitle || "Pfizer Project";
    const goal = ws.currentBrief?.goal || "";
    const sections = ws.currentBrief?.contentSections || [];
    const keyMessages = ws.currentBrief?.keyMessages || [];
    const bodyBlocks = [
      goal,
      ...sections,
      ...keyMessages.map(msg => `• ${msg}`),
    ].filter(Boolean);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${title}</title>
  <style>
    *{box-sizing:border-box} body{margin:0;font-family:Arial,sans-serif;background:#f8fafc;color:#0f172a}
    header{background:#003087;color:#fff;padding:24px 28px}
    h1{margin:0;font-size:30px;line-height:1.2}
    main{max-width:980px;margin:24px auto;background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:24px}
    p{line-height:1.7;margin:0 0 14px}
    footer{margin-top:20px;color:#64748b;font-size:12px}
  </style>
</head>
<body>
  <header>
    <h1>${title}</h1>
  </header>
  <main>
    ${bodyBlocks.map(block => `<p>${block}</p>`).join("\n    ")}
    <footer>Layout: ${ws.layout || "hero"} · Generated by Prompt Muse</footer>
  </main>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    const safeTitle = title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
    a.href = url;
    a.download = `${safeTitle || "pfizer-project"}.html`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
    toast.success("HTML export downloaded");
  };

  const handleSubmit = async () => {
    if (!agreed) return;

    const payload = {
      projectTitle: ws.currentBrief?.projectTitle || "Untitled Project",
      submitter: `${ws.user?.firstName || ""} ${ws.user?.lastName || ""}`.trim(),
      submitterEmail: ws.user?.email || "",
      country: ws.user?.country || "",
      buildType: ws.prelim.buildType || "",
      score: ws.reviewData?.overallScore || 0,
    };

    try {
      const { data, error } = await supabase.functions.invoke("notify-reviewer", { body: payload });
      if (error) throw new Error(error.message);
      appendAuditEvent({
        eventType: "notification",
        actor: ws.user?.email || "unknown-user",
        details: {
          reviewer_notified: true,
          simulated: Boolean(data?.simulated),
          message: data?.message || null,
        },
      });
      if (data?.simulated) {
        toast.message("Reviewer notification simulated (configure env vars for live email)");
      } else {
        toast.success("Reviewer notification sent");
      }
    } catch (err: any) {
      appendAuditEvent({
        eventType: "notification",
        actor: ws.user?.email || "unknown-user",
        details: {
          reviewer_notified: false,
          error: err?.message || "Notification call failed",
        },
      });
      toast.warning("Submission recorded, but reviewer notification failed");
    }

    ws.setSubmitted();
    appendAuditEvent({
      eventType: "submission",
      actor: ws.user?.email || "unknown-user",
      details: {
        projectTitle: ws.currentBrief?.projectTitle || "Untitled Project",
        score: ws.reviewData?.overallScore || 0,
        buildType: ws.prelim.buildType || "",
        audience: ws.prelim.audience || "",
      },
    });
    toast.success("Project submitted for review!");
  };

  return (
    <div className="flex-1 flex items-center justify-center overflow-y-auto p-7 animate-fade-up">
      <div className="bg-card border-[1.5px] border-border rounded-[20px] shadow-pf-md p-9 max-w-[500px] w-full">
        <h2 className="font-serif text-xl text-pf-dark mb-1">Export and Submit</h2>
        <p className="text-[13px] text-muted-foreground mb-5">
          Export the generated page as HTML, then submit for final review.
        </p>

        <div className="grid grid-cols-2 gap-2 mb-4">
          <MetaBox label="Type" value={ws.prelim.buildType || "—"} />
          <MetaBox label="Audience" value={ws.prelim.audience || "—"} />
          <MetaBox label="Region" value={ws.user?.country || "—"} />
          <MetaBox label="Score" value={ws.reviewData ? `${ws.reviewData.overallScore}/100` : "—"} />
        </div>

        <div className="bg-secondary border border-border rounded-md p-3 text-[12.5px] text-muted-foreground leading-relaxed max-h-[120px] overflow-y-auto mb-3">
          By submitting this project, I confirm that all content has been reviewed for brand compliance,
          accessibility standards (WCAG 2.1 AA), and regulatory requirements applicable to the target
          jurisdiction. I understand that the IT review team will perform a final assessment before
          publication. Any content flagged during the automated review has been addressed or acknowledged.
          This submission is subject to Pfizer's internal content governance policy.
        </div>

        <label className="flex items-center gap-2.5 mb-5 cursor-pointer">
          <input
            type="checkbox"
            checked={agreed}
            onChange={e => setAgreed(e.target.checked)}
            className="w-[15px] h-[15px] accent-primary cursor-pointer"
          />
          <span className="text-[13px] font-medium text-foreground">I agree to the terms and conditions</span>
        </label>

        <div className="grid grid-cols-2 gap-2">
          <button
            onClick={() => exportAuditJsonl()}
            className="w-full bg-card border border-border text-foreground rounded-md py-3 text-sm font-bold hover:border-primary hover:text-primary transition-all"
          >
            Export Audit Log
          </button>
          <button
            onClick={handleExportHtml}
            className="w-full bg-card border border-border text-foreground rounded-md py-3 text-sm font-bold hover:border-primary hover:text-primary transition-all"
          >
            Export HTML
          </button>
          <button
            onClick={handleSubmit}
            disabled={!agreed}
            className="w-full bg-btn-gradient text-primary-foreground rounded-md py-3 text-sm font-bold shadow-pf hover:shadow-pf-md transition-all disabled:opacity-40 disabled:cursor-not-allowed col-span-2"
          >
            Submit for Review
          </button>
        </div>
      </div>
    </div>
  );
};

function MetaBox({ label, value }: { label: string; value: string }) {
  return (
    <div className="bg-secondary border border-border rounded-md p-2.5">
      <div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground/60 mb-0.5">{label}</div>
      <div className="text-[13px] font-semibold text-foreground">{value}</div>
    </div>
  );
}

export default SubmitPanel;
